install: npm install
before_script:
  - docker build --rm --tag ftbbase ./base
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - node ./build build
sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker